/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DigitalAsset {
  export type AssetMetadataViewStruct = {
    cid: string;
    contentHash: BytesLike;
    registrationDate: BigNumberish;
    version: BigNumberish;
    isCertified: boolean;
    pendingCertifiers: AddressLike[];
  };

  export type AssetMetadataViewStructOutput = [
    cid: string,
    contentHash: string,
    registrationDate: bigint,
    version: bigint,
    isCertified: boolean,
    pendingCertifiers: string[]
  ] & {
    cid: string;
    contentHash: string;
    registrationDate: bigint;
    version: bigint;
    isCertified: boolean;
    pendingCertifiers: string[];
  };

  export type CertificationStruct = {
    certifier: AddressLike;
    timestamp: BigNumberish;
    comment: string;
  };

  export type CertificationStructOutput = [
    certifier: string,
    timestamp: bigint,
    comment: string
  ] & { certifier: string; timestamp: bigint; comment: string };

  export type CertificationWithTokenIdStruct = {
    tokenId: BigNumberish;
    certifier: AddressLike;
    timestamp: BigNumberish;
    comment: string;
  };

  export type CertificationWithTokenIdStructOutput = [
    tokenId: bigint,
    certifier: string,
    timestamp: bigint,
    comment: string
  ] & {
    tokenId: bigint;
    certifier: string;
    timestamp: bigint;
    comment: string;
  };
}

export interface DigitalAssetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "balanceOf"
      | "burn"
      | "eip712Domain"
      | "getApproved"
      | "isApprovedForAll"
      | "name"
      | "nonces"
      | "ownerOf"
      | "rbac"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "transferFrom"
      | "registerAsset"
      | "setCertifiers"
      | "certifyAsset"
      | "updateMetadata"
      | "burnAsset"
      | "getMetadata"
      | "getCertifications"
      | "getPendingCertifiers"
      | "hasCertified"
      | "getCertificationsByAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllCertified"
      | "Approval"
      | "ApprovalForAll"
      | "AssetBurned"
      | "AssetCertified"
      | "AssetRegistered"
      | "CertifiersSet"
      | "EIP712DomainChanged"
      | "MetadataUpdated"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "rbac", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [AddressLike, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCertifiers",
    values: [BigNumberish, AddressLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certifyAsset",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetadata",
    values: [BigNumberish, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnAsset",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertifications",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingCertifiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCertified",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificationsByAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rbac", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCertifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certifyAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingCertifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCertified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificationsByAddress",
    data: BytesLike
  ): Result;
}

export namespace AllCertifiedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetBurnedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetCertifiedEvent {
  export type InputTuple = [tokenId: BigNumberish, certifier: AddressLike];
  export type OutputTuple = [tokenId: bigint, certifier: string];
  export interface OutputObject {
    tokenId: bigint;
    certifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    registrant: AddressLike,
    cid: string
  ];
  export type OutputTuple = [tokenId: bigint, registrant: string, cid: string];
  export interface OutputObject {
    tokenId: bigint;
    registrant: string;
    cid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertifiersSetEvent {
  export type InputTuple = [tokenId: BigNumberish, certifiers: AddressLike[]];
  export type OutputTuple = [tokenId: bigint, certifiers: string[]];
  export interface OutputObject {
    tokenId: bigint;
    certifiers: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, newCid: string];
  export type OutputTuple = [tokenId: bigint, newCid: string];
  export interface OutputObject {
    tokenId: bigint;
    newCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DigitalAsset extends BaseContract {
  connect(runner?: ContractRunner | null): DigitalAsset;
  waitForDeployment(): Promise<this>;

  interface: DigitalAssetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  /**
   * See {IERC721-approve}.
   */
  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  /**
   * See {IERC721-balanceOf}.
   */
  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  /**
   * Burns `tokenId`. See {ERC721-_burn}. Requirements: - The caller must own `tokenId` or be an approved operator.
   */
  burn: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  /**
   * See {EIP-5267}. _Available since v4.9._
   */
  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  /**
   * See {IERC721-getApproved}.
   */
  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  /**
   * See {IERC721-isApprovedForAll}.
   */
  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  /**
   * See {IERC721Metadata-name}.
   */
  name: TypedContractMethod<[], [string], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  /**
   * See {IERC721-ownerOf}.
   */
  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  rbac: TypedContractMethod<[], [string], "view">;

  /**
   * See {IERC721-safeTransferFrom}.
   */
  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  /**
   * See {IERC721-safeTransferFrom}.
   */
  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  /**
   * See {IERC721-setApprovalForAll}.
   */
  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  /**
   * See {IERC165-supportsInterface}.
   */
  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  /**
   * See {IERC721Metadata-symbol}.
   */
  symbol: TypedContractMethod<[], [string], "view">;

  /**
   * See {IERC721Metadata-tokenURI}.
   */
  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  /**
   * See {IERC721-transferFrom}.
   */
  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAsset: TypedContractMethod<
    [
      to: AddressLike,
      cid: string,
      contentHash: BytesLike,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  setCertifiers: TypedContractMethod<
    [tokenId: BigNumberish, certifiers: AddressLike[], signature: BytesLike],
    [void],
    "nonpayable"
  >;

  certifyAsset: TypedContractMethod<
    [tokenId: BigNumberish, comment: string, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  updateMetadata: TypedContractMethod<
    [
      tokenId: BigNumberish,
      newCid: string,
      newHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  burnAsset: TypedContractMethod<
    [tokenId: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getMetadata: TypedContractMethod<
    [tokenId: BigNumberish],
    [DigitalAsset.AssetMetadataViewStructOutput],
    "view"
  >;

  getCertifications: TypedContractMethod<
    [tokenId: BigNumberish],
    [DigitalAsset.CertificationStructOutput[]],
    "view"
  >;

  getPendingCertifiers: TypedContractMethod<
    [tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  hasCertified: TypedContractMethod<
    [tokenId: BigNumberish, certifier: AddressLike],
    [boolean],
    "view"
  >;

  getCertificationsByAddress: TypedContractMethod<
    [certifier: AddressLike],
    [DigitalAsset.CertificationWithTokenIdStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "rbac"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [
      to: AddressLike,
      cid: string,
      contentHash: BytesLike,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCertifiers"
  ): TypedContractMethod<
    [tokenId: BigNumberish, certifiers: AddressLike[], signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "certifyAsset"
  ): TypedContractMethod<
    [tokenId: BigNumberish, comment: string, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMetadata"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      newCid: string,
      newHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnAsset"
  ): TypedContractMethod<
    [tokenId: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMetadata"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [DigitalAsset.AssetMetadataViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertifications"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [DigitalAsset.CertificationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingCertifiers"
  ): TypedContractMethod<[tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasCertified"
  ): TypedContractMethod<
    [tokenId: BigNumberish, certifier: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificationsByAddress"
  ): TypedContractMethod<
    [certifier: AddressLike],
    [DigitalAsset.CertificationWithTokenIdStructOutput[]],
    "view"
  >;

  getEvent(
    key: "AllCertified"
  ): TypedContractEvent<
    AllCertifiedEvent.InputTuple,
    AllCertifiedEvent.OutputTuple,
    AllCertifiedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "AssetBurned"
  ): TypedContractEvent<
    AssetBurnedEvent.InputTuple,
    AssetBurnedEvent.OutputTuple,
    AssetBurnedEvent.OutputObject
  >;
  getEvent(
    key: "AssetCertified"
  ): TypedContractEvent<
    AssetCertifiedEvent.InputTuple,
    AssetCertifiedEvent.OutputTuple,
    AssetCertifiedEvent.OutputObject
  >;
  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CertifiersSet"
  ): TypedContractEvent<
    CertifiersSetEvent.InputTuple,
    CertifiersSetEvent.OutputTuple,
    CertifiersSetEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdated"
  ): TypedContractEvent<
    MetadataUpdatedEvent.InputTuple,
    MetadataUpdatedEvent.OutputTuple,
    MetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "AllCertified(uint256)": TypedContractEvent<
      AllCertifiedEvent.InputTuple,
      AllCertifiedEvent.OutputTuple,
      AllCertifiedEvent.OutputObject
    >;
    AllCertified: TypedContractEvent<
      AllCertifiedEvent.InputTuple,
      AllCertifiedEvent.OutputTuple,
      AllCertifiedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "AssetBurned(uint256)": TypedContractEvent<
      AssetBurnedEvent.InputTuple,
      AssetBurnedEvent.OutputTuple,
      AssetBurnedEvent.OutputObject
    >;
    AssetBurned: TypedContractEvent<
      AssetBurnedEvent.InputTuple,
      AssetBurnedEvent.OutputTuple,
      AssetBurnedEvent.OutputObject
    >;

    "AssetCertified(uint256,address)": TypedContractEvent<
      AssetCertifiedEvent.InputTuple,
      AssetCertifiedEvent.OutputTuple,
      AssetCertifiedEvent.OutputObject
    >;
    AssetCertified: TypedContractEvent<
      AssetCertifiedEvent.InputTuple,
      AssetCertifiedEvent.OutputTuple,
      AssetCertifiedEvent.OutputObject
    >;

    "AssetRegistered(uint256,address,string)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "CertifiersSet(uint256,address[])": TypedContractEvent<
      CertifiersSetEvent.InputTuple,
      CertifiersSetEvent.OutputTuple,
      CertifiersSetEvent.OutputObject
    >;
    CertifiersSet: TypedContractEvent<
      CertifiersSetEvent.InputTuple,
      CertifiersSetEvent.OutputTuple,
      CertifiersSetEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "MetadataUpdated(uint256,string)": TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
    MetadataUpdated: TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
