/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DIDRegistry } from "./DIDRegistry";
export type { DigitalAsset } from "./DigitalAsset";
export type { RBAC } from "./RBAC";
export * as factories from "./factories";
export { DIDRegistry__factory } from "./factories/DIDRegistry__factory";
export { DigitalAsset__factory } from "./factories/DigitalAsset__factory";
export { RBAC__factory } from "./factories/RBAC__factory";
