/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DIDRegistry__factory } from "./DIDRegistry__factory";
export { DigitalAsset__factory } from "./DigitalAsset__factory";
export { RBAC__factory } from "./RBAC__factory";
